/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AssistanceRouteImport } from './routes/assistance'
import { Route as IndexRouteImport } from './routes/index'

const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistanceRoute = AssistanceRouteImport.update({
  id: '/assistance',
  path: '/assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistance': typeof AssistanceRoute
  '/confidentialite': typeof ConfidentialiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistance': typeof AssistanceRoute
  '/confidentialite': typeof ConfidentialiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistance': typeof AssistanceRoute
  '/confidentialite': typeof ConfidentialiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistance' | '/confidentialite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistance' | '/confidentialite'
  id: '__root__' | '/' | '/assistance' | '/confidentialite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistanceRoute: typeof AssistanceRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistance': {
      id: '/assistance'
      path: '/assistance'
      fullPath: '/assistance'
      preLoaderRoute: typeof AssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistanceRoute: AssistanceRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
